// ── Node type definitions ─────────────────────────────────
export const NODE_SCHEMA = {
  sine: {
    label: 'Sine',
    desc: 'pure tone',
    accent: '#b89a6a',
    synthDef: 'sonic-pi-beep',
    inputs: [],
    outputs: ['out'],
    params: {
      note:    { label: 'note', min: 24, max: 96,   step: 1,    val: 60 },
      amp:     { label: 'amp',  min: 0,  max: 1,    step: 0.01, val: 0.4 },
      attack:  { label: 'atk',  min: 0,  max: 5,    step: 0.1,  val: 0.1 },
      sustain: { label: 'sus',  min: 0.1,max: 9999, step: 1,    val: 9999 },
      release: { label: 'rel',  min: 0,  max: 10,   step: 0.1,  val: 1 },
    },
  },
  sine_osc: {
    label: 'Sine Osc',
    desc: 'modulatable sine',
    accent: '#b89a6a',
    synthDef: 'sine',
    inputs: [],
    outputs: ['out'],
    // Audio-rate modulation inputs (routed via audio buses)
    modInputs: ['freq', 'amp', 'phase'],
    params: {
      freq:  { label: 'freq',  min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:   { label: 'amp',   min: 0,   max: 1,     step: 0.01, val: 0.5 },
      phase: { label: 'pha',   min: 0,   max: 6.283, step: 0.01, val: 0 },
    },
  },
  saw_osc: {
    label: 'Saw Osc',
    desc: 'modulatable saw',
    accent: '#b89a6a',
    synthDef: 'saw_osc',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp'],
    params: {
      freq: { label: 'freq', min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:  { label: 'amp',  min: 0,   max: 1,     step: 0.01, val: 0.5 },
    },
  },
  pulse_osc: {
    label: 'Pulse Osc',
    desc: 'modulatable pulse',
    accent: '#b89a6a',
    synthDef: 'pulse_osc',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp', 'width'],
    params: {
      freq:  { label: 'freq',  min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:   { label: 'amp',   min: 0,   max: 1,     step: 0.01, val: 0.5 },
      width: { label: 'width', min: 0,   max: 1,     step: 0.01, val: 0.5 },
    },
  },
  tri_osc: {
    label: 'Tri Osc',
    desc: 'modulatable triangle',
    accent: '#b89a6a',
    synthDef: 'tri_osc',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp'],
    params: {
      freq: { label: 'freq', min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:  { label: 'amp',  min: 0,   max: 1,     step: 0.01, val: 0.5 },
    },
  },
  blip_osc: {
    label: 'Blip',
    desc: 'harmonic impulse',
    accent: '#b89a6a',
    synthDef: 'blip_osc',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp', 'numharm'],
    params: {
      freq:    { label: 'freq', min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:     { label: 'amp',  min: 0,   max: 1,     step: 0.01, val: 0.5 },
      numharm: { label: 'harm', min: 1,   max: 200,   step: 1,    val: 20 },
    },
  },
  formant_osc: {
    label: 'Formant',
    desc: 'vocal formant',
    accent: '#8ab0c8',
    synthDef: 'formant_osc',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp', 'formfreq', 'bwfreq'],
    params: {
      freq:     { label: 'freq', min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:      { label: 'amp',  min: 0,   max: 1,     step: 0.01, val: 0.5 },
      formfreq: { label: 'form', min: 0.1, max: 20000, step: 1,    val: 1760 },
      bwfreq:   { label: 'bw',   min: 0.1, max: 20000, step: 1,    val: 880 },
    },
  },
  dust_osc: {
    label: 'Dust',
    desc: 'random impulses',
    accent: '#c08880',
    synthDef: 'dust',
    inputs: [],
    outputs: ['out'],
    modInputs: ['density', 'amp'],
    params: {
      density: { label: 'dens', min: 0.1, max: 1000, step: 0.1, val: 1 },
      amp:     { label: 'amp',  min: 0,   max: 1,    step: 0.01, val: 0.5 },
    },
  },
  crackle_osc: {
    label: 'Crackle',
    desc: 'chaotic noise',
    accent: '#c08880',
    synthDef: 'crackle',
    inputs: [],
    outputs: ['out'],
    modInputs: ['chaos', 'amp'],
    params: {
      chaos: { label: 'chaos', min: 1, max: 2, step: 0.01, val: 1.5 },
      amp:   { label: 'amp',   min: 0, max: 1, step: 0.01, val: 0.5 },
    },
  },
  lfnoise0_osc: {
    label: 'LFNoise0',
    desc: 'stepped random',
    accent: '#7aab88',
    synthDef: 'lfnoise0',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp'],
    params: {
      freq: { label: 'rate', min: 0.01, max: 1000, step: 0.01, val: 4 },
      amp:  { label: 'amp',  min: 0,    max: 1,    step: 0.01, val: 0.5 },
    },
  },
  lfnoise1_osc: {
    label: 'LFNoise1',
    desc: 'linear random',
    accent: '#7aab88',
    synthDef: 'lfnoise1',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp'],
    params: {
      freq: { label: 'rate', min: 0.01, max: 1000, step: 0.01, val: 4 },
      amp:  { label: 'amp',  min: 0,    max: 1,    step: 0.01, val: 0.5 },
    },
  },
  lfnoise2_osc: {
    label: 'LFNoise2',
    desc: 'smooth random',
    accent: '#7aab88',
    synthDef: 'lfnoise2',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp'],
    params: {
      freq: { label: 'rate', min: 0.01, max: 1000, step: 0.01, val: 4 },
      amp:  { label: 'amp',  min: 0,    max: 1,    step: 0.01, val: 0.5 },
    },
  },
  lfo: {
    label: 'LFO',
    desc: 'low-freq oscillator',
    accent: '#7aab88',
    synthDef: 'lfo',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp', 'phase'],
    params: {
      freq:     { label: 'rate', min: 0.01, max: 40, step: 0.01, val: 1 },
      amp:      { label: 'amp',  min: 0,    max: 1,  step: 0.01, val: 0.5 },
      waveform: { label: 'wave', min: 0,    max: 3,  step: 1,    val: 0 },
      width:    { label: 'width',min: 0,    max: 1,  step: 0.01, val: 0.5 },
    },
  },
  white_noise_osc: {
    label: 'White Noise',
    desc: 'white noise',
    accent: '#c08880',
    synthDef: 'white_noise',
    inputs: [],
    outputs: ['out'],
    modInputs: ['amp'],
    params: {
      amp: { label: 'amp', min: 0, max: 1, step: 0.01, val: 0.5 },
    },
  },
  pink_noise_osc: {
    label: 'Pink Noise',
    desc: 'pink 1/f',
    accent: '#c08880',
    synthDef: 'pink_noise',
    inputs: [],
    outputs: ['out'],
    modInputs: ['amp'],
    params: {
      amp: { label: 'amp', min: 0, max: 1, step: 0.01, val: 0.5 },
    },
  },
  buchla_osc: {
    label: 'Buchla Osc',
    desc: 'waveshape morph',
    accent: '#c8a060',
    synthDef: 'buchla_osc',
    inputs: [],
    outputs: ['out'],
    modInputs: ['freq', 'amp', 'timbre'],
    params: {
      freq:   { label: 'freq',   min: 0.1, max: 20000, step: 0.1,  val: 440 },
      amp:    { label: 'amp',    min: 0,   max: 1,     step: 0.01, val: 0.5 },
      timbre: { label: 'timbre', min: 0,   max: 1,     step: 0.01, val: 0 },
    },
  },
  saw: {
    label: 'Saw',
    desc: 'sawtooth',
    accent: '#b89a6a',
    synthDef: 'sonic-pi-saw',
    inputs: [],
    outputs: ['out'],
    params: {
      note:    { label: 'note', min: 24, max: 96,   step: 1,    val: 60 },
      amp:     { label: 'amp',  min: 0,  max: 1,    step: 0.01, val: 0.25 },
      attack:  { label: 'atk',  min: 0,  max: 5,    step: 0.1,  val: 0.1 },
      sustain: { label: 'sus',  min: 0.1,max: 9999, step: 1,    val: 9999 },
      release: { label: 'rel',  min: 0,  max: 10,   step: 0.1,  val: 1 },
      cutoff:  { label: 'cut',  min: 30, max: 130,  step: 1,    val: 80 },
    },
  },
  bell: {
    label: 'Bell',
    desc: 'pretty bell',
    accent: '#8ab0c8',
    synthDef: 'sonic-pi-pretty_bell',
    inputs: [],
    outputs: ['out'],
    params: {
      note:    { label: 'note', min: 24, max: 96,  step: 1,    val: 72 },
      amp:     { label: 'amp',  min: 0,  max: 1,   step: 0.01, val: 0.5 },
      attack:  { label: 'atk',  min: 0,  max: 2,   step: 0.01, val: 0.01 },
      sustain: { label: 'sus',  min: 0,  max: 9999,step: 1,    val: 9999 },
      release: { label: 'rel',  min: 0,  max: 10,  step: 0.1,  val: 2 },
    },
  },
  blade: {
    label: 'Blade',
    desc: 'vibrato synth',
    accent: '#8ab0c8',
    synthDef: 'sonic-pi-blade',
    inputs: [],
    outputs: ['out'],
    params: {
      note:           { label: 'note',  min: 24, max: 96,  step: 1,    val: 64 },
      amp:            { label: 'amp',   min: 0,  max: 1,   step: 0.01, val: 0.2 },
      attack:         { label: 'atk',   min: 0,  max: 5,   step: 0.1,  val: 1 },
      sustain:        { label: 'sus',   min: 0.1,max: 9999,step: 1,    val: 9999 },
      release:        { label: 'rel',   min: 0,  max: 10,  step: 0.1,  val: 2 },
      cutoff:         { label: 'cut',   min: 30, max: 130, step: 1,    val: 80 },
      vibrato_rate:   { label: 'vib',   min: 0,  max: 20,  step: 0.5,  val: 3 },
      vibrato_depth:  { label: 'depth', min: 0,  max: 1,   step: 0.01, val: 0.06 },
    },
  },
  pad: {
    label: 'Pad',
    desc: 'dark ambience',
    accent: '#7aab88',
    synthDef: 'sonic-pi-dark_ambience',
    inputs: [],
    outputs: ['out'],
    params: {
      note:        { label: 'note', min: 24, max: 96,   step: 1,    val: 57 },
      amp:         { label: 'amp',  min: 0,  max: 1,    step: 0.01, val: 0.3 },
      attack:      { label: 'atk',  min: 0,  max: 10,   step: 0.5,  val: 3 },
      sustain:     { label: 'sus',  min: 0.1,max: 9999, step: 1,    val: 9999 },
      release:     { label: 'rel',  min: 0,  max: 20,   step: 0.5,  val: 5 },
      cutoff:      { label: 'cut',  min: 30, max: 130,  step: 1,    val: 72 },
      res:         { label: 'res',  min: 0,  max: 1,    step: 0.01, val: 0.05 },
      room:        { label: 'room', min: 0,  max: 1,    step: 0.01, val: 0.9 },
      reverb_damp: { label: 'damp', min: 0,  max: 1,    step: 0.01, val: 0.5 },
    },
  },
  hollow: {
    label: 'Hollow',
    desc: 'resonant texture',
    accent: '#7aab88',
    synthDef: 'sonic-pi-hollow',
    inputs: [],
    outputs: ['out'],
    params: {
      note:    { label: 'note', min: 24, max: 96,   step: 1,    val: 69 },
      amp:     { label: 'amp',  min: 0,  max: 1,    step: 0.01, val: 0.15 },
      attack:  { label: 'atk',  min: 0,  max: 10,   step: 0.5,  val: 2 },
      sustain: { label: 'sus',  min: 0.1,max: 9999, step: 1,    val: 9999 },
      release: { label: 'rel',  min: 0,  max: 20,   step: 0.5,  val: 5 },
      cutoff:  { label: 'cut',  min: 30, max: 130,  step: 1,    val: 80 },
      res:     { label: 'res',  min: 0,  max: 1,    step: 0.01, val: 0.1 },
    },
  },
  noise: {
    label: 'Noise',
    desc: 'brown 1/f²',
    accent: '#c08880',
    synthDef: 'sonic-pi-bnoise',
    inputs: [],
    outputs: ['out'],
    params: {
      amp:     { label: 'amp',  min: 0,  max: 1,    step: 0.01, val: 0.08 },
      attack:  { label: 'atk',  min: 0,  max: 5,    step: 0.5,  val: 1 },
      sustain: { label: 'sus',  min: 0.1,max: 9999, step: 1,    val: 9999 },
      release: { label: 'rel',  min: 0,  max: 20,   step: 0.5,  val: 5 },
      cutoff:  { label: 'cut',  min: 30, max: 130,  step: 1,    val: 95 },
      res:     { label: 'res',  min: 0,  max: 1,    step: 0.01, val: 0.05 },
    },
  },
  pluck: {
    label: 'Pluck',
    desc: 'string',
    accent: '#8ab0c8',
    synthDef: 'sonic-pi-pluck',
    inputs: [],
    outputs: ['out'],
    params: {
      note:    { label: 'note', min: 24, max: 96, step: 1,    val: 60 },
      amp:     { label: 'amp',  min: 0,  max: 1,  step: 0.01, val: 0.5 },
      sustain: { label: 'sus',  min: 0.1,max: 9999,step: 1,   val: 9999 },
      release: { label: 'rel',  min: 0,  max: 5,  step: 0.1,  val: 1 },
    },
  },
  // ── Sample player ──────────────────────────────────────
  sample_player: {
    label: 'Sampler',
    desc: 'sample player',
    accent: '#c89a60',
    synthDef: 'sample_player',
    width: 280,
    inputs: [],
    outputs: ['out'],
    modInputs: ['rate', 'amp'],
    params: {
      rate:      { label: 'rate', min: -4, max: 4, step: 0.01, val: 1 },
      amp:       { label: 'amp',  min: 0,  max: 1, step: 0.01, val: 0.5 },
      start_pos: { label: 'start', min: 0, max: 1, step: 0.001, val: 0, hidden: true },
      end_pos:   { label: 'end',   min: 0, max: 1, step: 0.001, val: 1, hidden: true },
      loop:      { label: 'loop',  min: 0, max: 1, step: 1, val: 1, hidden: true },
    },
  },
  // ── FX modules ─────────────────────────────────────────
  fx_reverb: {
    label: 'Reverb',
    desc: 'room reverb',
    accent: '#9b7abf',
    synthDef: 'sonic-pi-fx_reverb',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      mix:  { label: 'mix',  min: 0, max: 1, step: 0.01, val: 0.4 },
      room: { label: 'room', min: 0, max: 1, step: 0.01, val: 0.6 },
      damp: { label: 'damp', min: 0, max: 1, step: 0.01, val: 0.5 },
    },
  },
  fx_echo: {
    label: 'Echo',
    desc: 'delay + feedback',
    accent: '#9b7abf',
    synthDef: 'sonic-pi-fx_echo',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      mix:   { label: 'mix',   min: 0,    max: 1, step: 0.01, val: 1 },
      phase: { label: 'time',  min: 0.01, max: 2, step: 0.01, val: 0.25 },
      decay: { label: 'decay', min: 0,    max: 8, step: 0.1,  val: 2 },
    },
  },
  fx_lpf: {
    label: 'LPF',
    desc: 'low-pass filter',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_lpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1, val: 80 },
    },
  },
  fx_hpf: {
    label: 'HPF',
    desc: 'high-pass filter',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_hpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1, val: 30 },
    },
  },
  fx_bpf: {
    label: 'BPF',
    desc: 'band-pass filter',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_bpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      centre: { label: 'freq', min: 0, max: 130, step: 1, val: 60 },
      res:    { label: 'res',  min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_rlpf: {
    label: 'RLPF',
    desc: 'resonant low-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_rlpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1,    val: 80 },
      res:    { label: 'res', min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_rhpf: {
    label: 'RHPF',
    desc: 'resonant high-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_rhpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1,    val: 30 },
      res:    { label: 'res', min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_rbpf: {
    label: 'RBPF',
    desc: 'resonant band-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_rbpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      centre: { label: 'freq', min: 0, max: 130, step: 1,    val: 60 },
      res:    { label: 'res',  min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_nlpf: {
    label: 'NLPF',
    desc: 'normalized low-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_nlpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1, val: 80 },
    },
  },
  fx_nhpf: {
    label: 'NHPF',
    desc: 'normalized high-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_nhpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1, val: 30 },
    },
  },
  fx_nbpf: {
    label: 'NBPF',
    desc: 'normalized band-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_nbpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      centre: { label: 'freq', min: 0, max: 130, step: 1,    val: 60 },
      res:    { label: 'res',  min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_nrlpf: {
    label: 'NRLPF',
    desc: 'normalized resonant low-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_nrlpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1,    val: 80 },
      res:    { label: 'res', min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_nrhpf: {
    label: 'NRHPF',
    desc: 'normalized resonant high-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_nrhpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 0, max: 130, step: 1,    val: 30 },
      res:    { label: 'res', min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_nrbpf: {
    label: 'NRBPF',
    desc: 'normalized resonant band-pass',
    accent: '#bf9b7a',
    synthDef: 'sonic-pi-fx_nrbpf',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      centre: { label: 'freq', min: 0, max: 130, step: 1,    val: 60 },
      res:    { label: 'res',  min: 0, max: 1,   step: 0.01, val: 0.3 },
    },
  },
  fx_moog: {
    label: 'Moog',
    desc: 'moog ladder filter',
    accent: '#bf9b7a',
    synthDef: 'moog',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut', min: 20, max: 20000, step: 1,    val: 1000 },
      res:    { label: 'res', min: 0,  max: 4,     step: 0.01, val: 1 },
      mix:    { label: 'mix', min: 0,  max: 1,     step: 0.01, val: 1 },
    },
  },
  fx_moogff: {
    label: 'MoogFF',
    desc: 'moog ladder + gain',
    accent: '#bf9b7a',
    synthDef: 'moogff',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      cutoff: { label: 'cut',  min: 20, max: 20000, step: 1,    val: 1000 },
      res:    { label: 'res',  min: 0,  max: 4,     step: 0.01, val: 2 },
      gain:   { label: 'gain', min: 0,  max: 10,    step: 0.1,  val: 1 },
      mix:    { label: 'mix',  min: 0,  max: 1,     step: 0.01, val: 1 },
    },
  },
  fx_distortion: {
    label: 'Distort',
    desc: 'distortion',
    accent: '#bf7a7a',
    synthDef: 'sonic-pi-fx_distortion',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      distort: { label: 'dist', min: 0, max: 1,  step: 0.01, val: 0.5 },
      mix:     { label: 'mix',  min: 0, max: 1,  step: 0.01, val: 1 },
    },
  },
  fx_flanger: {
    label: 'Flanger',
    desc: 'flanger',
    accent: '#7abfbf',
    synthDef: 'sonic-pi-fx_flanger',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      phase:    { label: 'phase', min: 0,    max: 10, step: 0.1,  val: 4 },
      depth:    { label: 'depth', min: 0,    max: 5,  step: 0.1,  val: 5 },
      feedback: { label: 'fb',    min: 0,    max: 1,  step: 0.01, val: 0 },
      mix:      { label: 'mix',   min: 0,    max: 1,  step: 0.01, val: 1 },
    },
  },
  resonz: {
    label: 'Resonz',
    desc: 'resonant bandpass',
    accent: '#bf9b7a',
    synthDef: 'resonz',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    modInputs: ['cutoff', 'bw'],
    params: {
      cutoff: { label: 'freq', min: 20,   max: 20000, step: 1,    val: 1000 },
      bw:     { label: 'bwr',  min: 0.01, max: 2,     step: 0.01, val: 0.5 },
      mix:    { label: 'mix',  min: 0,    max: 1,      step: 0.01, val: 1 },
    },
  },
  comb: {
    label: 'Comb',
    desc: 'comb delay filter',
    accent: '#7abfbf',
    synthDef: 'comb',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    modInputs: ['delaytime', 'decaytime'],
    params: {
      delaytime: { label: 'delay', min: 0.0001, max: 1,  step: 0.001, val: 0.2 },
      decaytime: { label: 'decay', min: 0.01,   max: 20, step: 0.1,   val: 1 },
      mix:       { label: 'mix',   min: 0,       max: 1,  step: 0.01,  val: 0.5 },
    },
  },
  spectral_freeze: {
    label: 'Spectral Freeze',
    desc: 'freeze & hold spectrum',
    accent: '#7abfbf',
    synthDef: 'spectral_freeze',
    category: 'fx',
    needsFFTBuffer: true,
    inputs: ['in'],
    outputs: ['out'],
    params: {
      freeze: { label: 'freeze', min: 0, max: 1, step: 1,    val: 0, type: 'button' },
      mix:    { label: 'mix',    min: 0, max: 1, step: 0.01,  val: 1 },
      amp:    { label: 'amp',    min: 0, max: 1, step: 0.01,  val: 1 },
    },
  },
  lowpass_gate: {
    label: 'LP Gate',
    desc: 'lowpass gate',
    accent: '#a08060',
    synthDef: 'lowpass_gate',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    modInputs: ['level', 'gate'],
    params: {
      level: { label: 'level', min: 0,   max: 1, step: 0.01, val: 0.5 },
      gate:  { label: 'gate',  min: 0,   max: 1, step: 0.01, val: 1 },
      mode:  { label: 'mode',  min: 0,   max: 1, step: 0.01, val: 0.5 },
      res:   { label: 'res',   min: 0,   max: 1, step: 0.01, val: 0.3 },
      mix:   { label: 'mix',   min: 0,   max: 1, step: 0.01, val: 1 },
    },
  },
  // ── Utility modules ─────────────────────────────────────
  multiply: {
    label: 'Multiply',
    desc: 'signal gain',
    accent: '#a0a0a0',
    synthDef: 'multiply',
    category: 'fx',  // Uses FX routing (in_bus → out_bus)
    inputs: ['in'],
    outputs: ['out'],
    params: {
      gain: { label: 'gain', min: 0, max: 5000, step: 1, val: 100 },
    },
  },
  gain: {
    label: 'Gain',
    desc: 'amplifier',
    accent: '#a8b870',
    synthDef: 'ora_gain',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      amp: { label: 'amp', min: 0, max: 4, step: 0.01, val: 1.0 },
    },
  },
  attenuator: {
    label: 'Attenuator',
    desc: 'signal reducer',
    accent: '#8a8a9a',
    synthDef: 'ora_attenuator',
    category: 'fx',
    inputs: ['in'],
    outputs: ['out'],
    params: {
      level: { label: 'level', min: 0, max: 1, step: 0.01, val: 1.0 },
    },
  },
  print: {
    label: 'Print',
    desc: 'debug logger',
    accent: '#e07050',
    synthDef: 'print',
    category: 'fx',  // Uses FX routing (reads from in_bus)
    inputs: ['in'],
    outputs: [],
    params: {},
  },
  scope: {
    label: 'Scope',
    desc: 'oscilloscope',
    accent: '#6ab0b0',
    synthDef: 'ora_scope', // Buffer-based scope (BufWr+Phasor at audio rate)
    category: 'fx',        // Uses FX routing (reads from in_bus)
    width: 262,
    inputs: ['in'],
    outputs: [],            // Sink node (monitor only)
    params: {},
  },
  // ── Script modules ───────────────────────────────────────
  script: {
    label: 'Script',
    desc: 'code & patterns',
    accent: '#c8b060',
    synthDef: null,
    category: 'script',
    inputs: [],
    outputs: ['out'],
    params: {
      value: { label: 'val', min: 0, max: 127, step: 0.01, val: 0 },
    },
  },
  // ── Control modules ──────────────────────────────────────
  constant: {
    label: 'Constant',
    desc: 'fixed value',
    accent: '#d4a06a',
    synthDef: null,
    category: 'control',
    inputs: [],
    outputs: ['out'],
    params: {
      value: { label: 'val', min: 0, max: 127, step: 0.01, val: 60 },
    },
  },
  bang: {
    label: 'Bang',
    desc: 'trigger button',
    accent: '#e07050',
    synthDef: null,
    category: 'control',
    inputs: [],
    outputs: ['out'],
    params: {
      value: { label: 'val', min: 0, max: 1, step: 1, val: 0, hidden: true },
    },
  },
  midi_in: {
    label: 'MIDI In',
    desc: 'midi controller',
    accent: '#7a9fc8',
    synthDef: null,
    category: 'control',
    inputs: [],
    outputs: ['out'],
    params: {
      value: { label: 'val', min: 0, max: 127, step: 1, val: 0, hidden: true },
    },
  },
  envelope: {
    label: 'Envelope',
    desc: 'breakpoint editor',
    accent: '#c8b060',
    synthDef: null,
    category: 'control',
    width: 280,
    inputs: [],
    outputs: ['out'],
    params: {
      value: { label: 'out', min: 0, max: 1, step: 0.001, val: 0, hidden: true },
      trig:  { label: 'trig', min: 0, max: 1, step: 1, val: 0, hidden: true },
    },
  },
  pulser: {
    label: 'Pulser',
    desc: 'clock generator',
    accent: '#e0a050',
    synthDef: null,
    category: 'control',
    inputs: [],
    outputs: ['out'],
    params: {
      value: { label: 'pulse', min: 0, max: 1, step: 1, val: 0, hidden: true },
      rate:  { label: 'rate',  min: 0.01, max: 20, step: 0.01, val: 2 },
    },
  },
  sequencer: {
    label: 'Sequencer',
    desc: '5-step CV',
    accent: '#50b0e0',
    synthDef: null,
    category: 'control',
    width: 220,
    inputs: [],
    outputs: ['out'],
    params: {
      value:  { label: 'out',    min: 0, max: 127, step: 0.01, val: 0, hidden: true },
      trig:   { label: 'trig',   min: 0, max: 1,   step: 1,    val: 0, hidden: true },
      step1:  { label: 'step 1', min: 0, max: 127, step: 0.1,  val: 60 },
      step2:  { label: 'step 2', min: 0, max: 127, step: 0.1,  val: 64 },
      step3:  { label: 'step 3', min: 0, max: 127, step: 0.1,  val: 67 },
      step4:  { label: 'step 4', min: 0, max: 127, step: 0.1,  val: 72 },
      step5:  { label: 'step 5', min: 0, max: 127, step: 0.1,  val: 60 },
      length: { label: 'steps',  min: 3, max: 5,   step: 1,    val: 5 },
    },
  },
  audioOut: {
    label: 'Output',
    desc: 'audio destination',
    accent: '#7a7570',
    synthDef: null,
    inputs: ['L', 'R'],
    outputs: [],
    params: {},
  },
};

// ── Module categories for the instrument panel ───────────
export const MODULE_CATEGORIES = [
  {
    id: 'oscillators',
    label: 'Oscillators',
    desc: 'basic waveforms',
    types: ['sine', 'sine_osc', 'buchla_osc', 'saw'],
  },
  {
    id: 'samplers',
    label: 'Samplers',
    desc: 'sample playback',
    types: ['sample_player'],
  },
  {
    id: 'instruments',
    label: 'Instruments',
    desc: 'melodic voices',
    types: ['bell', 'blade', 'pluck'],
  },
  {
    id: 'textures',
    label: 'Textures',
    desc: 'pads & noise',
    types: ['pad', 'hollow', 'noise'],
  },
  {
    id: 'filters',
    label: 'Filters',
    desc: 'frequency shaping',
    types: ['fx_lpf', 'fx_hpf', 'fx_bpf', 'fx_rlpf', 'fx_rhpf', 'fx_rbpf', 'fx_moog', 'fx_moogff', 'fx_nlpf', 'fx_nhpf', 'fx_nbpf', 'fx_nrlpf', 'fx_nrhpf', 'fx_nrbpf', 'resonz', 'lowpass_gate'],
  },
  {
    id: 'fx',
    label: 'Effects',
    desc: 'time & space',
    types: ['fx_reverb', 'fx_echo', 'fx_distortion', 'fx_flanger', 'comb', 'spectral_freeze'],
  },
  {
    id: 'utility',
    label: 'Utility',
    desc: 'signal tools',
    types: ['gain', 'attenuator', 'multiply', 'print', 'scope'],
  },
  {
    id: 'scripting',
    label: 'Scripting',
    desc: 'code & patterns',
    types: ['script'],
  },
  {
    id: 'modulation',
    label: 'Modulation',
    desc: 'LFOs & modulators',
    types: ['lfo', 'lfnoise0_osc', 'lfnoise1_osc', 'lfnoise2_osc'],
  },
  {
    id: 'control',
    label: 'Control',
    desc: 'modulation sources',
    types: ['constant', 'envelope', 'pulser', 'sequencer', 'bang', 'midi_in'],
  },
];
